### ISSUE TITLE
Choose a REST framework

### ISSUE THREAD

**Issue by zeroXten** [pki-io/api#1]

**Comment by kalloc** [comment]
my  vote for native web api (ServerHandler from go/cgi)
it will allow to make it easy to re-use code

**Comment by thanasisk** [comment]
I vote for Martini - ease of coding
https://github.com/go-martini/martini

**Comment by kalloc** [comment]
It will be standalone application or pluggable package?

**Comment by zeroXten** [comment]
Martini looks nice. +1

**Comment by kalloc** [comment]
:)  
it's depended of our needs
if we would like package, we should use go/cgi
but if we would like just web app, we can use everything

**Comment by zeroXten** [comment]
The api itself is an app. It would probably make use of the existing pki.io packages.

**Comment by zeroXten** [comment]
Lets just go with martini. Kalloc expressed approval on IRC, others have had enough time to object ;)

**Comment by thanasisk** [comment]
Awesome!
